Feature branch
zdrale/Responsive-Web-Page pull request #2
Opened 2020-10-02 13:11 UTC by zdrale

Clone of The NextWeb webpage with a responsive layout. The project contains the following components.

Used flex, grid, and float for alignment and layout
Used semantic HTML for header, main content, and footer

2020-10-02 17:38 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello team!
Amazing job on this project, I am impressed! 👏 
Good and descriptive commits and readme 👍 
Linters are green 🟢 
Good use of HTML tags 💯 
Clean and readable code 🥇 

However, we need to make some changes in order to get this project approved 💪 
Please, check my comments below 👇  apply the changes and resubmit the project for a new code review ⏩ 

## Changes
- In the main section, we should see the logo of the publication 'TNW', that disappears on medium screens.
    It contains TWN logo at the top left corner of the row ([link to page](https://thenextweb.com/))
    TWN logo disappears ([link to page](https://thenextweb.com/))
- Try to wrap all your media queries, I have counted 29 media queries. You should use only 2, one for 768px and another for 1024px
- The main section before the second breakpoint has a problem with the font size, kindly modify it
![Capture](https://user-images.githubusercontent.com/56809963/94952451-4d409780-04e6-11eb-8865-fab3b992d8b9.PNG)
- In the Apps, Gear, Tech, etc... section, please add links to the list
![Capture1](https://user-images.githubusercontent.com/56809963/94952598-837e1700-04e6-11eb-8f9e-d0c6f109284f.PNG)
- And kindly modify the height of the main images in those sections to make it equal to the original
Original:
![Capture3](https://user-images.githubusercontent.com/56809963/94952729-b9230000-04e6-11eb-8b65-f670884daa50.PNG)

Your project:
![Capture2](https://user-images.githubusercontent.com/56809963/94952741-c04a0e00-04e6-11eb-990e-e2f5a56a7750.PNG)

2020-10-02 17:38 UTC, javitocor commented on Assets/style.css
> +}
Please, do not use `!important`, it is only applicable in special cases. Kindly remove it

2020-10-02 17:38 UTC, javitocor commented on Assets/style.css
> +}
same here!

2020-10-02 17:38 UTC, javitocor commented on Assets/style.css
> +}
Same here!

2020-10-02 17:38 UTC, javitocor commented on index.html
> +          <li class="mnr-list-item"><a href="#" class="counter">00:20:30:20</a></li>
Please do not use `inline styling`, you can move the style into the CSS file and improve your code's readability

2020-10-05 13:45 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: Hello Team!! Great effort on the project!

## Required Changes
### [Mandatory] :red_circle: 

- [x] Section Latest funding is not matching the original in mobile version
![image](https://user-images.githubusercontent.com/25774518/95085513-f1902d00-06e4-11eb-9954-389a05852889.png)

- [x] Latest funding show an extra element in mobile version
![image](https://user-images.githubusercontent.com/25774518/95085570-05d42a00-06e5-11eb-9341-4a39ce868064.png)

- [x] The logo black rectagle does not match the navbar height
![image](https://user-images.githubusercontent.com/25774518/95085693-31571480-06e5-11eb-8d00-36fa73d84c85.png)

- [x] Elementes have extra white space
![image](https://user-images.githubusercontent.com/25774518/95085824-5ba8d200-06e5-11eb-87e8-607797cebf15.png)

- [x] Latest deals are missing the correct information
![image](https://user-images.githubusercontent.com/25774518/95085944-7d09be00-06e5-11eb-8bfd-6f991bb65590.png)

- [ ] Footer does not match original in mobile version
![image](https://user-images.githubusercontent.com/25774518/95086028-9ad72300-06e5-11eb-8eb9-dd9b60a31c00.png)

- [ ] Social media does not match original style
![image](https://user-images.githubusercontent.com/25774518/95086146-c0642c80-06e5-11eb-9f5a-3a86ae37c578.png)

- [x] Missing Margin between navbar and 3 image section
![image](https://user-images.githubusercontent.com/25774518/95086379-0d480300-06e6-11eb-9dcb-b95f40ce86f5.png)

- [x] Latest funding does not match original
![image](https://user-images.githubusercontent.com/25774518/95086468-251f8700-06e6-11eb-874b-8e42bfb50dea.png)

- [ ] Navbar is nod displaying as original in tablet mode
![image](https://user-images.githubusercontent.com/25774518/95086603-4c765400-06e6-11eb-802c-a1c81c1670fa.png)

- [ ] Icons not displaying properly
![image](https://user-images.githubusercontent.com/25774518/95086722-70399a00-06e6-11eb-8d50-3d7ca1d9f204.png)

### [Comments] :green_circle: 
- Is a great habit to use the Browser Media Query Inspector mode and the default values for media queries  1440, 1024, 768, 320 to check if the project looks as intended in different screen sizes. This also a great tool to test the original website and observer the changes.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-05 13:48 UTC, zdrale commented
> # Status: Changes Required 
> ##   Hello Team!! Great effort on the project!
> ## Required Changes
> ### [Mandatory] 
> * [ ]  Section Latest funding is not matching the original in mobile version
>   ![image](https://user-images.githubusercontent.com/25774518/95085513-f1902d00-06e4-11eb-9954-389a05852889.png)
> * [ ]  Latest funding show an extra element in mobile version
>   ![image](https://user-images.githubusercontent.com/25774518/95085570-05d42a00-06e5-11eb-9341-4a39ce868064.png)
> * [ ]  The logo black rectagle does not match the navbar height
>   ![image](https://user-images.githubusercontent.com/25774518/95085693-31571480-06e5-11eb-8d00-36fa73d84c85.png)
> * [ ]  Elementes have extra white space
>   ![image](https://user-images.githubusercontent.com/25774518/95085824-5ba8d200-06e5-11eb-87e8-607797cebf15.png)
> * [ ]  Latest deals are missing the correct information
>   ![image](https://user-images.githubusercontent.com/25774518/95085944-7d09be00-06e5-11eb-8bfd-6f991bb65590.png)
> * [ ]  Footer does not match original in mobile version
>   ![image](https://user-images.githubusercontent.com/25774518/95086028-9ad72300-06e5-11eb-8eb9-dd9b60a31c00.png)
> * [ ]  Social media does not match original style
>   ![image](https://user-images.githubusercontent.com/25774518/95086146-c0642c80-06e5-11eb-9f5a-3a86ae37c578.png)
> * [ ]  Missing Margin between navbar and 3 image section
>   ![image](https://user-images.githubusercontent.com/25774518/95086379-0d480300-06e6-11eb-9dcb-b95f40ce86f5.png)
> * [ ]  Latest funding does not match original
>   ![image](https://user-images.githubusercontent.com/25774518/95086468-251f8700-06e6-11eb-874b-8e42bfb50dea.png)
> * [ ]  Navbar is nod displaying as original in tablet mode
>   ![image](https://user-images.githubusercontent.com/25774518/95086603-4c765400-06e6-11eb-802c-a1c81c1670fa.png)
> * [ ]  Icons not displaying properly
>   ![image](https://user-images.githubusercontent.com/25774518/95086722-70399a00-06e6-11eb-8d50-3d7ca1d9f204.png)
> 
> ### [Comments] 
> * Is a great habit to use the Browser Media Query Inspector mode and the default values for media queries  1440, 1024, 768, 320 to check if the project looks as intended in different screen sizes. This also a great tool to test the original website and observer the changes.
> 
> ## Keep up the great work  and Happy Coding  !!

>

2020-10-06 01:34 UTC, jubaan requested changes
# Status: Changes Required :recycle:

Wow!! it's looking awesome! :clap: :clap: 

## Requested changes
## :wave: :wave: Hello!! Great effort!!

### [Mandatory] :red_circle: 

- [x] The live preview link is not Updated. This creates the appearance that the previously required changes have not been made.

### [Comments] :green_circle: 

- The project shows as intended in firefox. still in web browsers like chrome or opera, and probably safari is having a horizontal scrolling effect. This should not be happening. This might be something related to a CSS property that needs the vendor prefix for the specific property.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-10-06 02:06 UTC, cyonii commented
Thank you for your thorough and informative review.

We cannot seem to notice the horizontal scroll effect you commented on, we have tested in Firefox, Chrome, and Safari on both desktop and mobile. Could you be any clearer?

2020-10-06 02:19 UTC, javitocor approved these changes
# STATUS APPROVED 🥇 ⭐ 

Great job in this project, team! 👍 
You have met all the requirements 👏  and you can move into the next project! ⏩ 
Congratulations! 🥳 
Remember to fill up the completion form 📑  on your dashboard

Good luck! 😃

2020-10-06 02:32 UTC, jubaan commented
> Thank you for your thorough and informative review.
> 
> We cannot seem to notice the horizontal scroll effect you commented on, we have tested in Firefox, Chrome, and Safari on both desktop and mobile. Could you be any clearer?

To reproduce it use the Media Query Inspector, (do not resize the browser window).

[Video of the issue](https://www.loom.com/share/af2a65c6c17942edb219d8ab288132bd)

2020-10-06 07:09 UTC, merged